zfpga1.c: Follow signature change of class_create
work-shared/imx6qdl-variscite-som/kernel-source/include/linux/init.h:180:22: error: passing argument 1 of 'class_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
  180 | #define THIS_MODULE (&__this_module)
      |                     ~^~~~~~~~~~~~~~~
      |                      |
      |                      struct module *

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>